rom_config: '../../../extract/eur/config.yaml'
build_path: '../../../build/eur'
delinks_path: '../../../build/eur/delinks'
main_module:
  name: main
  object: '../../../build/eur/build/arm9.bin'
  hash: '636a932beea0d69d'
  delinks: delinks.txt
  symbols: symbols.txt
  relocations: relocs.txt
autoloads:
- kind: Itcm
  name: itcm
  object: '../../../build/eur/build/itcm.bin'
  hash: f9a042e1b0cf3569
  delinks: itcm/delinks.txt
  symbols: itcm/symbols.txt
  relocations: itcm/relocs.txt
- kind: Dtcm
  name: dtcm
  object: '../../../build/eur/build/dtcm.bin'
  hash: '24bc190fa0255f53'
  delinks: dtcm/delinks.txt
  symbols: dtcm/symbols.txt
  relocations: dtcm/relocs.txt
overlays:
- id: 0
  name: ov000
  object: '../../../build/eur/build/arm9_ov000.bin'
  hash: '573cdec05509ee60'
  delinks: overlays/ov000/delinks.txt
  symbols: overlays/ov000/symbols.txt
  relocations: overlays/ov000/relocs.txt
- id: 1
  name: ov001
  object: '../../../build/eur/build/arm9_ov001.bin'
  hash: a3051d1c98a8cc28
  delinks: overlays/ov001/delinks.txt
  symbols: overlays/ov001/symbols.txt
  relocations: overlays/ov001/relocs.txt
- id: 2
  name: ov002
  object: '../../../build/eur/build/arm9_ov002.bin'
  hash: a23195ec85f9efca
  delinks: overlays/ov002/delinks.txt
  symbols: overlays/ov002/symbols.txt
  relocations: overlays/ov002/relocs.txt
- id: 3
  name: ov003
  object: '../../../build/eur/build/arm9_ov003.bin'
  hash: a3051d1c98a8cc28
  delinks: overlays/ov003/delinks.txt
  symbols: overlays/ov003/symbols.txt
  relocations: overlays/ov003/relocs.txt
- id: 4
  name: ov004
  object: '../../../build/eur/build/arm9_ov004.bin'
  hash: a3051d1c98a8cc28
  delinks: overlays/ov004/delinks.txt
  symbols: overlays/ov004/symbols.txt
  relocations: overlays/ov004/relocs.txt
- id: 5
  name: ov005
  object: '../../../build/eur/build/arm9_ov005.bin'
  hash: '43475e1456c73048'
  delinks: overlays/ov005/delinks.txt
  symbols: overlays/ov005/symbols.txt
  relocations: overlays/ov005/relocs.txt
- id: 6
  name: ov006
  object: '../../../build/eur/build/arm9_ov006.bin'
  hash: deb869b971ab10d2
  delinks: overlays/ov006/delinks.txt
  symbols: overlays/ov006/symbols.txt
  relocations: overlays/ov006/relocs.txt
- id: 7
  name: ov007
  object: '../../../build/eur/build/arm9_ov007.bin'
  hash: '1ade7243776cebf7'
  delinks: overlays/ov007/delinks.txt
  symbols: overlays/ov007/symbols.txt
  relocations: overlays/ov007/relocs.txt
- id: 8
  name: ov008
  object: '../../../build/eur/build/arm9_ov008.bin'
  hash: e2dc75c3ad656a66
  delinks: overlays/ov008/delinks.txt
  symbols: overlays/ov008/symbols.txt
  relocations: overlays/ov008/relocs.txt
- id: 9
  name: ov009
  object: '../../../build/eur/build/arm9_ov009.bin'
  hash: e8868bc599dff408
  delinks: overlays/ov009/delinks.txt
  symbols: overlays/ov009/symbols.txt
  relocations: overlays/ov009/relocs.txt
- id: 10
  name: ov010
  object: '../../../build/eur/build/arm9_ov010.bin'
  hash: '523e8c11932b0b21'
  delinks: overlays/ov010/delinks.txt
  symbols: overlays/ov010/symbols.txt
  relocations: overlays/ov010/relocs.txt
- id: 11
  name: ov011
  object: '../../../build/eur/build/arm9_ov011.bin'
  hash: c5acc69086fd353d
  delinks: overlays/ov011/delinks.txt
  symbols: overlays/ov011/symbols.txt
  relocations: overlays/ov011/relocs.txt
- id: 12
  name: ov012
  object: '../../../build/eur/build/arm9_ov012.bin'
  hash: f62a68f76e491194
  delinks: overlays/ov012/delinks.txt
  symbols: overlays/ov012/symbols.txt
  relocations: overlays/ov012/relocs.txt
- id: 13
  name: ov013
  object: '../../../build/eur/build/arm9_ov013.bin'
  hash: e98772e4cf003ffc
  delinks: overlays/ov013/delinks.txt
  symbols: overlays/ov013/symbols.txt
  relocations: overlays/ov013/relocs.txt
- id: 14
  name: ov014
  object: '../../../build/eur/build/arm9_ov014.bin'
  hash: '87bdec40d5f83f95'
  delinks: overlays/ov014/delinks.txt
  symbols: overlays/ov014/symbols.txt
  relocations: overlays/ov014/relocs.txt
- id: 15
  name: ov015
  object: '../../../build/eur/build/arm9_ov015.bin'
  hash: '27e01a4d79dcc9fc'
  delinks: overlays/ov015/delinks.txt
  symbols: overlays/ov015/symbols.txt
  relocations: overlays/ov015/relocs.txt
- id: 16
  name: ov016
  object: '../../../build/eur/build/arm9_ov016.bin'
  hash: '5bd54631096d9994'
  delinks: overlays/ov016/delinks.txt
  symbols: overlays/ov016/symbols.txt
  relocations: overlays/ov016/relocs.txt
- id: 17
  name: ov017
  object: '../../../build/eur/build/arm9_ov017.bin'
  hash: '6547465a9def02bb'
  delinks: overlays/ov017/delinks.txt
  symbols: overlays/ov017/symbols.txt
  relocations: overlays/ov017/relocs.txt
- id: 18
  name: ov018
  object: '../../../build/eur/build/arm9_ov018.bin'
  hash: a884003387964899
  delinks: overlays/ov018/delinks.txt
  symbols: overlays/ov018/symbols.txt
  relocations: overlays/ov018/relocs.txt
- id: 19
  name: ov019
  object: '../../../build/eur/build/arm9_ov019.bin'
  hash: a3051d1c98a8cc28
  delinks: overlays/ov019/delinks.txt
  symbols: overlays/ov019/symbols.txt
  relocations: overlays/ov019/relocs.txt
- id: 20
  name: ov020
  object: '../../../build/eur/build/arm9_ov020.bin'
  hash: df895b0a67861567
  delinks: overlays/ov020/delinks.txt
  symbols: overlays/ov020/symbols.txt
  relocations: overlays/ov020/relocs.txt
- id: 21
  name: ov021
  object: '../../../build/eur/build/arm9_ov021.bin'
  hash: a4bcb8c1a3354ab4
  delinks: overlays/ov021/delinks.txt
  symbols: overlays/ov021/symbols.txt
  relocations: overlays/ov021/relocs.txt
- id: 22
  name: ov022
  object: '../../../build/eur/build/arm9_ov022.bin'
  hash: a3051d1c98a8cc28
  delinks: overlays/ov022/delinks.txt
  symbols: overlays/ov022/symbols.txt
  relocations: overlays/ov022/relocs.txt
- id: 23
  name: ov023
  object: '../../../build/eur/build/arm9_ov023.bin'
  hash: a3051d1c98a8cc28
  delinks: overlays/ov023/delinks.txt
  symbols: overlays/ov023/symbols.txt
  relocations: overlays/ov023/relocs.txt
- id: 24
  name: ov024
  object: '../../../build/eur/build/arm9_ov024.bin'
  hash: a3051d1c98a8cc28
  delinks: overlays/ov024/delinks.txt
  symbols: overlays/ov024/symbols.txt
  relocations: overlays/ov024/relocs.txt
- id: 25
  name: ov025
  object: '../../../build/eur/build/arm9_ov025.bin'
  hash: '81be6fb286230e08'
  delinks: overlays/ov025/delinks.txt
  symbols: overlays/ov025/symbols.txt
  relocations: overlays/ov025/relocs.txt
- id: 26
  name: ov026
  object: '../../../build/eur/build/arm9_ov026.bin'
  hash: '2c354d8731e68098'
  delinks: overlays/ov026/delinks.txt
  symbols: overlays/ov026/symbols.txt
  relocations: overlays/ov026/relocs.txt
- id: 27
  name: ov027
  object: '../../../build/eur/build/arm9_ov027.bin'
  hash: a3051d1c98a8cc28
  delinks: overlays/ov027/delinks.txt
  symbols: overlays/ov027/symbols.txt
  relocations: overlays/ov027/relocs.txt
- id: 28
  name: ov028
  object: '../../../build/eur/build/arm9_ov028.bin'
  hash: a3051d1c98a8cc28
  delinks: overlays/ov028/delinks.txt
  symbols: overlays/ov028/symbols.txt
  relocations: overlays/ov028/relocs.txt
- id: 29
  name: ov029
  object: '../../../build/eur/build/arm9_ov029.bin'
  hash: a3051d1c98a8cc28
  delinks: overlays/ov029/delinks.txt
  symbols: overlays/ov029/symbols.txt
  relocations: overlays/ov029/relocs.txt
- id: 30
  name: ov030
  object: '../../../build/eur/build/arm9_ov030.bin'
  hash: a3051d1c98a8cc28
  delinks: overlays/ov030/delinks.txt
  symbols: overlays/ov030/symbols.txt
  relocations: overlays/ov030/relocs.txt
- id: 31
  name: ov031
  object: '../../../build/eur/build/arm9_ov031.bin'
  hash: a3051d1c98a8cc28
  delinks: overlays/ov031/delinks.txt
  symbols: overlays/ov031/symbols.txt
  relocations: overlays/ov031/relocs.txt
- id: 32
  name: ov032
  object: '../../../build/eur/build/arm9_ov032.bin'
  hash: a3051d1c98a8cc28
  delinks: overlays/ov032/delinks.txt
  symbols: overlays/ov032/symbols.txt
  relocations: overlays/ov032/relocs.txt
- id: 33
  name: ov033
  object: '../../../build/eur/build/arm9_ov033.bin'
  hash: a3051d1c98a8cc28
  delinks: overlays/ov033/delinks.txt
  symbols: overlays/ov033/symbols.txt
  relocations: overlays/ov033/relocs.txt
- id: 34
  name: ov034
  object: '../../../build/eur/build/arm9_ov034.bin'
  hash: a3051d1c98a8cc28
  delinks: overlays/ov034/delinks.txt
  symbols: overlays/ov034/symbols.txt
  relocations: overlays/ov034/relocs.txt
- id: 35
  name: ov035
  object: '../../../build/eur/build/arm9_ov035.bin'
  hash: a3051d1c98a8cc28
  delinks: overlays/ov035/delinks.txt
  symbols: overlays/ov035/symbols.txt
  relocations: overlays/ov035/relocs.txt
- id: 36
  name: ov036
  object: '../../../build/eur/build/arm9_ov036.bin'
  hash: a3051d1c98a8cc28
  delinks: overlays/ov036/delinks.txt
  symbols: overlays/ov036/symbols.txt
  relocations: overlays/ov036/relocs.txt
